### ISSUE TITLE
compiling for lm4f120

### ISSUE THREAD

**Issue by raako71** [rei-vilo/DateTime_Library#1]
I've put this library in my sketchbook folder and the opened the MSP432_RTC example and had the following compile errors:

<pre>In file included from MSP432_RTC.cpp:81:0:
H:\Energia\libraries\DateTime/DateTimeLibrary.h:49:18: fatal error: WiFi.h: No such file or directory</pre>

I got around this by changing line 46 in DateTimeLibrary.h to 

<pre>#define INCLUDE_NTP 0</pre>

next error:

<pre>H:\Energia\libraries\DateTime\DateTimeLibrary.cpp: In member function 'void DateTime::setTime(tm)':
H:\Energia\libraries\DateTime\DateTimeLibrary.cpp:255:25: error: 'timeEpoch' was not declared in this scope</pre>

not sure as to fixing this..

**Comment by rei-vilo** [comment]
Please download latest commit 9e66b812f5.

**Comment by raako71** [comment]
hey it compiles now :)
Although I had it set to the MSP430 board and it failed with:
MSP432_RTC.cpp:78:18: fatal error: time.h: No such file or directory
compilation terminated.

**Comment by rei-vilo** [comment]
MSP430 is not supported.

**Comment by raako71** [comment]
:thumbsup:
thanks for that
