### ISSUE TITLE
LM4F120

### ISSUE THREAD

**Issue by raako71** [rei-vilo/DateTime_Library#2]
I've got the sample code for the MSP432_RTC loaded on an LM4F120. The code will compile and display on the serial monitor fine, just the RTC doesn't increment :/

**Comment by rei-vilo** [comment]
Sorry, I couldn't replicate the issue. Everything works fine for me.

> Connecting to LAN-SSID....connected
> IP address............192.168.1.31
> MAC address...11:22:33:44:55:66
> Set time...
> Fri Sep 25 20:29:22 2015
> Fri Sep 25 20:29:23 2015
> Fri Sep 25 20:29:24 2015
> Fri Sep 25 20:29:25 2015
> Fri Sep 25 20:29:26 2015
> Fri Sep 25 20:29:27 2015

**Comment by raako71** [comment]
Ok I've tried again and its working. great Success!!!
