### ISSUE TITLE
Library does not support TM4C1294XL by default

### ISSUE THREAD

**Issue by CorBer** [rei-vilo/DateTime_Library#3]
Hi,

This library should work also on the TM4C1294XL launchpad but due to a simple missing definition it does not. 
If the part of the code where a check is made which board the code is compiled for the following is added :
|| defined(**TM4C1294NCPDT**)

and the following is set 
# define INCLUDE_NTP 0

This code runs perfectly on a TM4C1294XL launchpad when connected to the internet.

regards
Cor

**Comment by rei-vilo** [comment]
I'm not sure to understand your point. 

Does it concern the core **date and time functions**? In that case, the TM4C129 LaunchPad is already supported through `__TM4C129XNCZAD__`.

If it is related to the **NTP server**, connection through Ethernet differs from WiFi, hence `INCLUDE_NTP` set to 0.

**Comment by CorBer** [comment]
Hi Rei,

The TM4C1294XL launchpad I am using gave - before I changed the code as
stated a "platform not supported" error also when I set INCLUDE_NTP to 0 ...

Cor

On 17 October 2015 at 11:27, Rei Vilo notifications@github.com wrote:

> I'm not sure to understand your point.
> 
> Does it concern the core _date and time functions_? In that case, the
> TM4C129 LaunchPad is already supported through **TM4C129XNCZAD**.
> 
> If it is related to the _NTP server_, connection through Ethernet differs
> from WiFi, hence INCLUDE_NTP set to 0.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rei-vilo/DateTimeLibrary/issues/3#issuecomment-148898658
> .

## 

---

RegiStax Free Image Processing Software
http://www.astronomie.be/registax

---

**Comment by CorBer** [comment]
The support for the TM4C129 in the current setup is not for all TM4C129
launchpads.

**TM4C129XNCZAD**. is the _TM4C129x Connected Development Kit (DK-TM4C129X)_

the *TM4C1294NCPDT *I am reporting is for the

*EK-TM4C1294XL Connected LaunchPad *
They are 2 different launchpad with many things that are the same and as
stated, the library works fine if this is added.

cheers
Cor

On 17 October 2015 at 12:54, CorandAylinsGarden registax@gmail.com wrote:

> Hi Rei,
> 
> The TM4C1294XL launchpad I am using gave - before I changed the code as
> stated a "platform not supported" error also when I set INCLUDE_NTP to 0 ...
> 
> Cor
> 
> On 17 October 2015 at 11:27, Rei Vilo notifications@github.com wrote:
> 
> > I'm not sure to understand your point.
> > 
> > Does it concern the core _date and time functions_? In that case, the
> > TM4C129 LaunchPad is already supported through **TM4C129XNCZAD**.
> > 
> > If it is related to the _NTP server_, connection through Ethernet
> > differs from WiFi, hence INCLUDE_NTP set to 0.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/rei-vilo/DateTimeLibrary/issues/3#issuecomment-148898658
> > .
> 
> ## 
> 
> ---
> 
> RegiStax Free Image Processing Software
> http://www.astronomie.be/registax
> 
> ---

## 

---

RegiStax Free Image Processing Software
http://www.astronomie.be/registax

---

**Comment by rei-vilo** [comment]
See 52ad3b07217ef9347b1f87283bb72be3f740a039

**Comment by CorBer** [comment]
Thanks !

On 17 October 2015 at 14:41, Rei Vilo notifications@github.com wrote:

> Closed #3 https://github.com/rei-vilo/DateTimeLibrary/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rei-vilo/DateTimeLibrary/issues/3#event-438217918.

## 

---

RegiStax Free Image Processing Software
http://www.astronomie.be/registax

---

**Comment by CorBer** [comment]
Did you also change the same elif in the DateTimeLibrary.cpp at line 183 ??

On 17 October 2015 at 15:20, CorandAylinsGarden registax@gmail.com wrote:

> Thanks !
> 
> On 17 October 2015 at 14:41, Rei Vilo notifications@github.com wrote:
> 
> > Closed #3 https://github.com/rei-vilo/DateTimeLibrary/issues/3.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/rei-vilo/DateTimeLibrary/issues/3#event-438217918.
> 
> ## 
> 
> ---
> 
> RegiStax Free Image Processing Software
> http://www.astronomie.be/registax
> 
> ---

## 

---

RegiStax Free Image Processing Software
http://www.astronomie.be/registax

---

**Comment by rei-vilo** [comment]
Good catch! Done with 957849e8b7ae28256bf24be4c8adae0b5e754900

**Comment by CorBer** [comment]
Neat.

On 17 October 2015 at 16:04, Rei Vilo notifications@github.com wrote:

> Good catch! Done with 957849e
> https://github.com/rei-vilo/DateTimeLibrary/commit/957849e8b7ae28256bf24be4c8adae0b5e754900
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rei-vilo/DateTimeLibrary/issues/3#issuecomment-148917844
> .

## 

---

RegiStax Free Image Processing Software
http://www.astronomie.be/registax

---

**Comment by CorBer** [comment]
You forgot the starting and trailing __ chars for the define ... If you add
those it compilesas planned (just tested in Visual Studio)

On 17 October 2015 at 12:54, CorandAylinsGarden registax@gmail.com wrote:

> Hi Rei,
> 
> The TM4C1294XL launchpad I am using gave - before I changed the code as
> stated a "platform not supported" error also when I set INCLUDE_NTP to 0 ...
> 
> Cor
> 
> On 17 October 2015 at 11:27, Rei Vilo notifications@github.com wrote:
> 
> > I'm not sure to understand your point.
> > 
> > Does it concern the core _date and time functions_? In that case, the
> > TM4C129 LaunchPad is already supported through **TM4C129XNCZAD**.
> > 
> > If it is related to the _NTP server_, connection through Ethernet
> > differs from WiFi, hence INCLUDE_NTP set to 0.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/rei-vilo/DateTimeLibrary/issues/3#issuecomment-148898658
> > .
> 
> ## 
> 
> ---
> 
> RegiStax Free Image Processing Software
> http://www.astronomie.be/registax
> 
> ---

## 

---

RegiStax Free Image Processing Software
http://www.astronomie.be/registax

---

**Comment by rei-vilo** [comment]
Why don't you submit a pull request instead? It would be easier as you have ta board to test it! Thank you.

**Comment by CorBer** [comment]
Hi

I am simply not experienced enough it seems... Never used github

Cheers
Cor

**Comment by rei-vilo** [comment]
Perfect time to learn!
