### ISSUE TITLE
CCS Cloud compile error

### ISSUE THREAD

**Issue by Beck-Sisyphus** [rei-vilo/DateTime_Library#4]
@workspace/CC3200_NTP/CC3200_NTP.ino:154:41: error: 'getTimeNTP' was not declared in this scope

![screen shot 2015-12-12 at 2 32 37 pm](https://cloud.githubusercontent.com/assets/5952569/11764245/52e5a062-a0dd-11e5-9e74-5728ecbf0cb5.png)

May I know where do you compile it?

**Comment by rei-vilo** [comment]
See line 46 of DateTimeLibrary.h
